/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.AlunoDAO;
import Model.Aluno;
import Util.LimitaDigitosNum;
import Util.LimiteDigitos;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author FND
 */
public class AlunoView extends javax.swing.JInternalFrame {

    Aluno aluno;
    AlunoDAO alunoDAO;
    List<Aluno> listaAluno;
    
    public AlunoView() {
        initComponents();
        alunoDAO = new AlunoDAO();
        listaAluno = new ArrayList<>();
        this.setVisible(true);
        atualizarTabelaAluno();
        txtNome.setDocument(new LimiteDigitos(60));
        txtEmail.setDocument(new LimiteDigitos(60));
        txtCurso.setDocument(new LimiteDigitos(50));
        txtTurma.setDocument(new LimiteDigitos(20));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbRa = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lbCurso = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        lbTurma = new javax.swing.JLabel();
        txtTurma = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtRa = new javax.swing.JFormattedTextField();
        pnl2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAluno = new javax.swing.JTable();

        setClosable(true);
        setTitle("Alunos");
        setPreferredSize(new java.awt.Dimension(650, 550));

        lbCodigo.setText("ID:");
        lbCodigo.setEnabled(false);

        lbNome.setText("Nome:");
        lbNome.setEnabled(false);

        lbRa.setText("R.A:");
        lbRa.setEnabled(false);

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtNome.setEnabled(false);

        lbCurso.setText("Curso:");
        lbCurso.setEnabled(false);

        txtCurso.setEnabled(false);

        lbTurma.setText("Turma:");
        lbTurma.setEnabled(false);

        txtTurma.setEnabled(false);
        txtTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTurmaKeyTyped(evt);
            }
        });

        lbEmail.setText("E-Mail:");
        lbEmail.setEnabled(false);

        txtEmail.setEnabled(false);

        txtRa.setFormatterFactory(setFormatoRa());
        txtRa.setEnabled(false);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail)
                    .addComponent(txtNome)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbRa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbTurma)
                                .addGap(18, 18, 18)
                                .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo)
                    .addComponent(lbRa)
                    .addComponent(txtRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCurso)
                    .addComponent(lbTurma)
                    .addComponent(txtTurma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public static DefaultFormatterFactory setFormatoRa(){  
        MaskFormatter comFoco = null;  
        try   
        {   
            comFoco = new MaskFormatter("##-#####"); 
            comFoco.setPlaceholderCharacter('_');
        }   
        catch (Exception pe) { }  
        DefaultFormatterFactory factory = new DefaultFormatterFactory(comFoco, comFoco);  
        return factory;  
    } 
    
     public void atualizarTabelaAluno(){
        aluno = new Aluno();
        
        try {
            listaAluno = alunoDAO.ListaAluno();
        } catch (SQLException ex) {
            Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
 
        String dados[][] = new String[listaAluno.size()][5];
        int i = 0;
        for(Aluno aluno : listaAluno){
            dados[i][0] = String.valueOf(aluno.getCodigoAluno());
            dados[i][1] = aluno.getNomeAluno();
            dados[i][2] = aluno.getRaAluno();
            dados[i][3] = aluno.getCursoAluno();
            dados[i][4] = aluno.getTurmaAluno();
            i++;
        }
        
        String tituloColuna[] = {"ID", "Nome", "R.A", "Curso", "Turma"};
        DefaultTableModel tabelaAluno = new DefaultTableModel();
        tabelaAluno.setDataVector(dados, tituloColuna);
        tbAluno.setModel(new DefaultTableModel(dados, tituloColuna){
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        });
        
        tbAluno.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbAluno.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbAluno.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbAluno.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbAluno.getColumnModel().getColumn(4).setPreferredWidth(100);
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbAluno.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbAluno.setRowHeight(25);
        tbAluno.updateUI();
    }
    
    
    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        aluno = new Aluno();
        String strRa = "__-_____";
        
        try {
                aluno = alunoDAO.recuperar(txtRa.getText());
            } catch (SQLException ex) {
                Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        if(aluno!=null){
            JOptionPane.showMessageDialog(null, "RA já Cadastrado!");
            txtRa.setText("");
            txtRa.requestFocusInWindow();
        } else if(txtRa.getText().isEmpty() || strRa.equals(txtRa.getText())){
            JOptionPane.showMessageDialog(null, "Preencha o RA!");
            txtRa.requestFocusInWindow();
            
        } else if(txtNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome!");
            txtNome.requestFocusInWindow();
        } else if(txtCurso.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Curso!");
            txtCurso.requestFocusInWindow();
        } else if(txtTurma.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Turma!");
            txtTurma.requestFocusInWindow();
        } else if(txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o E-Mail!");
            txtEmail.requestFocusInWindow();
        } else if(txtCodigo.getText().isEmpty()){
            aluno = new Aluno();
            aluno.setNomeAluno(txtNome.getText());
            aluno.setEmailAluno(txtEmail.getText());
            aluno.setCategoriaAluno("Aluno");
            aluno.setRaAluno(txtRa.getText());
            aluno.setCursoAluno(txtCurso.getText());
            aluno.setTurmaAluno(txtTurma.getText());

            try {
                alunoDAO.salvar(aluno);
            } catch (SQLException ex) {
                Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            atualizarTabelaAluno();
            preparaSalvareCancelar();
            desativaCampos();
            limpaCamposAluno();
            
            
        } else{
            aluno = new Aluno();
            aluno.setCodigoAluno(Integer.parseInt(txtCodigo.getText()));
            aluno.setNomeAluno(txtNome.getText());
            aluno.setEmailAluno(txtEmail.getText());
            aluno.setCategoriaAluno("Aluno");
            aluno.setRaAluno(txtRa.getText());
            aluno.setCursoAluno(txtCurso.getText());
            aluno.setTurmaAluno(txtTurma.getText());
            
            
            try {
                alunoDAO.alterar(aluno);
            } catch (SQLException ex) {
                Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            atualizarTabelaAluno();
            preparaSalvareCancelar();
            desativaCampos();
            
            
        } 
       
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tbAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlunoMouseClicked

        txtCodigo.setText(tbAluno.getValueAt(tbAluno.getSelectedRow(),0).toString());
        try {   
            aluno = alunoDAO.AlunoById(Integer.parseInt(txtCodigo.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNome.setText(aluno.getNomeAluno());
        txtRa.setText(aluno.getRaAluno());
        txtCurso.setText(aluno.getCursoAluno());
        txtTurma.setText(aluno.getTurmaAluno());
        txtEmail.setText(aluno.getEmailAluno());
        
        preparaSelecaoTabela();
    }//GEN-LAST:event_tbAlunoMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um aluno!");
        } else{
            aluno = new Aluno();
            aluno.setCodigoAluno(Integer.parseInt(txtCodigo.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " +txtNome.getText());
            
            if(confirma ==0){
                
                try {
                    alunoDAO.excluir(aluno);
                } catch (SQLException ex) {
                    Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
                
                atualizarTabelaAluno();
                limpaCamposAluno();
                preparaExcluir();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        preparaAlterar();
        ativaCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        limpaCamposAluno();
        preparaNovo();
        ativaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposAluno();
        preparaSalvareCancelar();
        desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTurmaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTurmaKeyTyped
        
    }//GEN-LAST:event_txtTurmaKeyTyped

    public void limpaCamposAluno(){
        txtNome.setText("");
        txtCodigo.setText("");
        txtRa.setText("");
        txtCurso.setText("");
        txtTurma.setText("");
        txtEmail.setText("");
        
    }
     
    public void ativaCampos(){
        lbNome.setEnabled(true);
        txtNome.setEnabled(true);
        lbRa.setEnabled(true);
        txtRa.setEnabled(true);
        lbCurso.setEnabled(true);
        txtCurso.setEnabled(true);
        lbTurma.setEnabled(true);
        txtTurma.setEnabled(true);
        lbEmail.setEnabled(true);
        txtEmail.setEnabled(true);
    }
    
    public void desativaCampos(){
        lbNome.setEnabled(false);
        txtNome.setEnabled(false);
        lbRa.setEnabled(false);
        txtRa.setEnabled(false);
        lbCurso.setEnabled(false);
        txtCurso.setEnabled(false);
        lbTurma.setEnabled(false);
        txtTurma.setEnabled(false);
        lbEmail.setEnabled(false);
        txtEmail.setEnabled(false);
    }
    
    public void preparaNovo(){
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbAluno.setEnabled(false);
        tbAluno.clearSelection();
    }
    
    public void preparaSalvareCancelar(){
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tbAluno.setEnabled(true);
    }
    
    public void preparaSelecaoTabela(){
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    }
    
    public void preparaAlterar(){
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbAluno.setEnabled(false);
        tbAluno.clearSelection();
    }
    
    public void preparaExcluir(){
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRa;
    private javax.swing.JLabel lbTurma;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JTable tbAluno;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRa;
    private javax.swing.JTextField txtTurma;
    // End of variables declaration//GEN-END:variables
}
