/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CategoriaDAO;
import Model.Categoria;
import Util.LimitaDigitosNum;
import Util.LimiteDigitos;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FND
 */
public class CategoriaView extends javax.swing.JInternalFrame {

   Categoria categoria;
   CategoriaDAO categoriaDAO;
   List<Categoria> listaCategoria;
    
    public CategoriaView() {
        initComponents();
        this.setVisible(true);
        categoriaDAO = new CategoriaDAO();
        txtCategoria.setDocument(new LimiteDigitos(40));
        atualizarTabelaCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbId = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCategoria = new javax.swing.JTable();

        setClosable(true);
        setTitle("Categoria de Atividades");
        setToolTipText("");

        lbId.setText("ID:");
        lbId.setEnabled(false);

        lbCategoria.setText("Categoria:");
        lbCategoria.setEnabled(false);

        txtCategoria.setEnabled(false);

        txtId.setEnabled(false);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tbCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCategoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbCategoria))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbId)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCategoria)
                                .addGap(95, 95, 95)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void atualizarTabelaCategoria(){
        categoria = new Categoria();
        

       try {
           listaCategoria = categoriaDAO.ListaCategoria();
       } catch (SQLException ex) {
           Logger.getLogger(CategoriaView.class.getName()).log(Level.SEVERE, null, ex);
       }

 
        String dados[][] = new String[listaCategoria.size()][2];
        int i = 0;
        for(Categoria categoria : listaCategoria){
            dados[i][0] = String.valueOf(categoria.getCodigoCategoria());
            dados[i][1] = categoria.getNomeCategoria();
            i++;
        }
        
        String tituloColuna[] = {"ID", "CATEGORIA"};
        DefaultTableModel tabelaCategoria = new DefaultTableModel();
        tabelaCategoria.setDataVector(dados, tituloColuna);
        tbCategoria.setModel(new DefaultTableModel(dados, tituloColuna){
            boolean[] canEdit = new boolean[]{
                false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        });
        
        tbCategoria.getColumnModel().getColumn(0).setPreferredWidth(70);
        tbCategoria.getColumnModel().getColumn(1).setPreferredWidth(500);
        
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbCategoria.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbCategoria.setRowHeight(25);
        tbCategoria.updateUI();
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(txtCategoria.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha os campos!");
            txtCategoria.requestFocusInWindow();
        } else if(txtId.getText().isEmpty()){
            categoria = new Categoria();
            categoria.setNomeCategoria(txtCategoria.getText());
            
            
            try {
                categoriaDAO.salvar(categoria);
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
           JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
           atualizarTabelaCategoria();
           preparaSalvareCancelar();
           desativaCampos();
           limpaCamposCategoria();
        } 
        else{
            categoria = new Categoria();
            categoria.setCodigoCategoria(Integer.parseInt(txtId.getText()));
            categoria.setNomeCategoria(txtCategoria.getText());

            
            
            try {
                categoriaDAO.alterar(categoria);
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
           
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            atualizarTabelaCategoria();
            preparaSalvareCancelar();
            desativaCampos();
            limpaCamposCategoria();
            
        } 
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCamposCategoria();
        preparaNovo();
        ativaCampos();
        txtCategoria.requestFocusInWindow();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        preparaNovo();
        ativaCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um curso!");
        } else{
            categoria = new Categoria();
            categoria.setCodigoCategoria(Integer.parseInt(txtId.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " +txtCategoria.getText());
            
            if(confirma ==0){
                
                
                
                try {
                    categoriaDAO.excluir(categoria);
                } catch (SQLException ex) {
                    Logger.getLogger(CategoriaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                
               
                JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
                
                atualizarTabelaCategoria();
                limpaCamposCategoria();
                preparaExcluir();
            }
        }
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposCategoria();
        preparaSalvareCancelar();
        desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tbCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCategoriaMouseClicked
       txtId.setText(tbCategoria.getValueAt(tbCategoria.getSelectedRow(),0).toString());
       txtCategoria.setText(tbCategoria.getValueAt(tbCategoria.getSelectedRow(),1).toString());
       preparaSelecaoTabela();
    }//GEN-LAST:event_tbCategoriaMouseClicked

    public void limpaCamposCategoria(){
        txtId.setText("");
        txtCategoria.setText("");
    }
    
    public void ativaCampos(){
        lbCategoria.setEnabled(true);
        txtCategoria.setEnabled(true);
    }
    
    public void desativaCampos(){
        lbCategoria.setEnabled(false);
        txtCategoria.setEnabled(false);
    }
    
    public void preparaNovo(){
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbCategoria.setEnabled(false);
        tbCategoria.clearSelection();
    }
    
    public void preparaSalvareCancelar(){
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tbCategoria.setEnabled(true);
    }
    
    public void preparaSelecaoTabela(){
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    }
    
    public void preparaAlterar(){
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbCategoria.setEnabled(false);
        tbCategoria.clearSelection();
    }
    
    public void preparaExcluir(){
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbId;
    private javax.swing.JTable tbCategoria;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
