/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ComunidadeDAO;
import Model.Comunidade;
import Util.LimitaDigitosNum;
import Util.LimiteDigitos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author FND
 */
public class ComunidadeView extends javax.swing.JInternalFrame {

    Comunidade comunidade;
    ComunidadeDAO comunidadeDAO;
    List<Comunidade> listaComunidade;
    
    public ComunidadeView() {
        initComponents();
        comunidadeDAO = new ComunidadeDAO();
        listaComunidade = new ArrayList<>();
        txtNome.setDocument(new LimiteDigitos(60));
        txtTelefone.setDocument(new LimiteDigitos(15));
        txtEmail.setDocument(new LimiteDigitos(60));
        txtInstituicao.setDocument(new LimiteDigitos(60));
        txtTelefone.setDocument(new LimiteDigitos(12));
        txtCpf.setDocument(new LimiteDigitos(11));
        this.setVisible(true);
        atualizarTabelaComunidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lbTelefone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtInstituicao = new javax.swing.JTextField();
        lbInstituicao = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        pnl2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbComunidade = new javax.swing.JTable();

        setClosable(true);
        setTitle("Comunidade");
        setPreferredSize(new java.awt.Dimension(650, 550));

        lbCodigo.setText("ID:");
        lbCodigo.setEnabled(false);

        lbNome.setText("Nome:");
        lbNome.setEnabled(false);

        lbCpf.setText("CPF:");
        lbCpf.setEnabled(false);

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNome.setEnabled(false);

        lbTelefone.setText("Telefone:");
        lbTelefone.setEnabled(false);

        lbEmail.setText("E-Mail:");
        lbEmail.setEnabled(false);

        txtEmail.setEnabled(false);

        txtInstituicao.setEnabled(false);

        lbInstituicao.setText("Instituição:");
        lbInstituicao.setEnabled(false);

        txtTelefone.setEnabled(false);

        txtCpf.setEnabled(false);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbInstituicao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInstituicao)
                            .addComponent(txtNome)
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl1Layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(lbCpf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 87, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo)
                    .addComponent(lbCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInstituicao)
                    .addComponent(txtInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbComunidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbComunidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbComunidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbComunidade);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void atualizarTabelaComunidade(){
        comunidade = new Comunidade();
        
        
        try {
            listaComunidade = comunidadeDAO.ListaComunidade();
        } catch (SQLException ex) {
            Logger.getLogger(ComunidadeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        String dados[][] = new String[listaComunidade.size()][5];
        int i = 0;
        for(Comunidade comunidade : listaComunidade){
            dados[i][0] = String.valueOf(comunidade.getCodigoComunidade());
            dados[i][1] = comunidade.getNomeComunidade();
            dados[i][2] = String.valueOf(comunidade.getCpfComunidade());
            dados[i][3] = comunidade.getInstituicaoComunidade();
            dados[i][4] = comunidade.getTelefoneComunidade();
            i++;
        }
        
        String tituloColuna[] = {"ID", "Nome", "CPF", "Instituição", "Telefone"};
        DefaultTableModel tabelaComunidade = new DefaultTableModel();
        tabelaComunidade.setDataVector(dados, tituloColuna);
        tbComunidade.setModel(new DefaultTableModel(dados, tituloColuna){
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        });
        
        tbComunidade.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbComunidade.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbComunidade.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbComunidade.getColumnModel().getColumn(3).setPreferredWidth(300);
        tbComunidade.getColumnModel().getColumn(4).setPreferredWidth(140);
     
        
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbComunidade.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbComunidade.setRowHeight(25);
        tbComunidade.updateUI();
    }
    
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        comunidade = new Comunidade();
       
        try {
            comunidade = comunidadeDAO.recuperar(txtCpf.getText());
        } catch (SQLException ex) {
            Logger.getLogger(ComunidadeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(txtCpf.getText().isEmpty() || txtCpf.getText().length()<11){
            JOptionPane.showMessageDialog(null, "Preencha o CPF Corretamente!");
            txtCpf.requestFocusInWindow();
        } else if(txtNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome!");
            txtNome.requestFocusInWindow();
        } else if(txtTelefone.getText().isEmpty() || txtTelefone.getText().length()<11){
            JOptionPane.showMessageDialog(null, "Preencha o Telefone Corretamente(DDD+Número)!");
            txtTelefone.requestFocusInWindow();
        } else if(txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o E-Mail!");
            txtEmail.requestFocusInWindow();
        } else if(txtInstituicao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Instituição!");
            txtInstituicao.requestFocusInWindow();
        }
        
        else if(txtCodigo.getText().isEmpty()){
            if(comunidade!=null){
            JOptionPane.showMessageDialog(null, "CPF já Cadastrado!");
            txtCpf.setText("");
            txtCpf.requestFocusInWindow();
        } else{
            comunidade = new Comunidade();
            comunidade.setNomeComunidade(txtNome.getText());
            comunidade.setEmailComunidade(txtEmail.getText());
            comunidade.setTipoComunidade("Comunidade");
            comunidade.setCpfComunidade(txtCpf.getText());
            comunidade.setInstituicaoComunidade(txtInstituicao.getText());
            comunidade.setTelefoneComunidade(txtTelefone.getText());

           
            try {
                comunidadeDAO.salvar(comunidade);
            } catch (SQLException ex) {
                Logger.getLogger(ComunidadeView.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            atualizarTabelaComunidade();
            preparaSalvareCancelar();
            desativaCampos();
            limpaCamposComunidade();
                }
        } else{
            comunidade = new Comunidade();
            comunidade.setCodigoComunidade(Integer.parseInt(txtCodigo.getText()));
            comunidade.setNomeComunidade(txtNome.getText());
            comunidade.setEmailComunidade(txtEmail.getText());
            comunidade.setTipoComunidade("Comunidade");
            comunidade.setCpfComunidade(txtCpf.getText());
            comunidade.setInstituicaoComunidade(txtInstituicao.getText());
            comunidade.setTelefoneComunidade(txtTelefone.getText());
            
            
           
            try {
                comunidadeDAO.alterar(comunidade);
            } catch (SQLException ex) {
                Logger.getLogger(ComunidadeView.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            atualizarTabelaComunidade();
            preparaSalvareCancelar();
            desativaCampos();
            
        } 
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um participante!");
        } else{
            comunidade = new Comunidade();
            comunidade.setCodigoComunidade(Integer.parseInt(txtCodigo.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " +txtNome.getText());
            
            if(confirma ==0){
                
                try {
                    comunidadeDAO.excluir(comunidade);
                } catch (SQLException ex) {
                    Logger.getLogger(ComunidadeView.class.getName()).log(Level.SEVERE, null, ex);
                }
               

                JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
                atualizarTabelaComunidade();
                limpaCamposComunidade();
                preparaExcluir();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tbComunidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbComunidadeMouseClicked
        
        txtCodigo.setText(tbComunidade.getValueAt(tbComunidade.getSelectedRow(),0).toString());
        try {
            comunidade = comunidadeDAO.ComunidadeById(Integer.parseInt(txtCodigo.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(ComunidadeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtNome.setText(comunidade.getNomeComunidade());
        txtCpf.setText(comunidade.getCpfComunidade());
        txtTelefone.setText(comunidade.getTelefoneComunidade());
        txtEmail.setText(comunidade.getEmailComunidade());
        txtInstituicao.setText(comunidade.getInstituicaoComunidade());
        
        /*txtCodigo.setText(tbComunidade.getValueAt(tbComunidade.getSelectedRow(),0).toString());
        txtNome.setText(tbComunidade.getValueAt(tbComunidade.getSelectedRow(),1).toString());
        txtEmail.setText(tbComunidade.getValueAt(tbComunidade.getSelectedRow(),2).toString());
        txtCpf.setText(tbComunidade.getValueAt(tbComunidade.getSelectedRow(),3).toString());
        txtInstituicao.setText(tbComunidade.getValueAt(tbComunidade.getSelectedRow(),4).toString());
        txtTelefone.setText(tbComunidade.getValueAt(tbComunidade.getSelectedRow(),5).toString());*/
        preparaSelecaoTabela();
    }//GEN-LAST:event_tbComunidadeMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtCpf.requestFocusInWindow();
        limpaCamposComunidade();
        preparaNovo();
        ativaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposComunidade();
        preparaSalvareCancelar();
        desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       preparaAlterar();
       ativaCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    public void limpaCamposComunidade(){
        txtCodigo.setText("");
        txtNome.setText("");
        txtCpf.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtInstituicao.setText("");
    }
    
     public void ativaCampos(){
        lbNome.setEnabled(true);
        txtNome.setEnabled(true);
        lbCpf.setEnabled(true);
        txtCpf.setEnabled(true);
        lbInstituicao.setEnabled(true);
        txtInstituicao.setEnabled(true);
        lbTelefone.setEnabled(true);
        txtTelefone.setEnabled(true);
        lbEmail.setEnabled(true);
        txtEmail.setEnabled(true);
    }
    
    public void desativaCampos(){
        lbNome.setEnabled(false);
        txtNome.setEnabled(false);
        lbCpf.setEnabled(false);
        txtCpf.setEnabled(false);
        lbInstituicao.setEnabled(false);
        txtInstituicao.setEnabled(false);
        lbTelefone.setEnabled(false);
        txtTelefone.setEnabled(false);
        lbEmail.setEnabled(false);
        txtEmail.setEnabled(false);
    }
    
    public void preparaNovo(){
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbComunidade.setEnabled(false);
        tbComunidade.clearSelection();
    }
    
    public void preparaSalvareCancelar(){
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tbComunidade.setEnabled(true);
    }
    
    public void preparaSelecaoTabela(){
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    }
    
    public void preparaAlterar(){
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbComunidade.setEnabled(false);
        tbComunidade.clearSelection();
    }
    
    public void preparaExcluir(){
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbInstituicao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JTable tbComunidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtInstituicao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
