/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CursoDAO;
import DAO.EventoDAO;
import Model.Curso;
import Model.Evento;
import Util.LimiteDigitos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author FND
 */
public class EventoView extends javax.swing.JInternalFrame {

    Evento evento;
    EventoDAO eventoDAO;
    List<Evento> listaEvento;
    CursoDAO cursoDAO;
    List<Curso> listaCurso;
    
    public EventoView() {
        initComponents();
        this.setVisible(true);
        eventoDAO = new EventoDAO();
        cursoDAO = new CursoDAO();
        listaEvento = new ArrayList<>();
        listaCurso = new ArrayList<>();
        txtEvento.setDocument(new LimiteDigitos(80));
        txtResponsavel.setDocument(new LimiteDigitos(60));
        atualizarTabelaEvento();
        preencherComboCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbEvento = new javax.swing.JLabel();
        lbInicio = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtEvento = new javax.swing.JTextField();
        lbTermino = new javax.swing.JLabel();
        lbResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        cbCurso = new javax.swing.JComboBox();
        lbArea = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox();
        txtInicio = new javax.swing.JFormattedTextField();
        txtTermino = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEvento = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro de Eventos");
        setPreferredSize(new java.awt.Dimension(650, 550));

        lbCodigo.setText("Código:");
        lbCodigo.setEnabled(false);

        lbEvento.setText("Evento:");
        lbEvento.setEnabled(false);

        lbInicio.setText("Inicio:");
        lbInicio.setEnabled(false);

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtEvento.setEnabled(false);

        lbTermino.setText("Término:");
        lbTermino.setEnabled(false);

        lbResponsavel.setText("Responsável:");
        lbResponsavel.setEnabled(false);

        txtResponsavel.setEnabled(false);

        cbCurso.setEnabled(false);
        cbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoActionPerformed(evt);
            }
        });

        lbArea.setText("Área:");
        lbArea.setEnabled(false);

        lbStatus.setText("Status:");
        lbStatus.setEnabled(false);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        cbStatus.setEnabled(false);

        txtInicio.setFormatterFactory(setFormatoData());
        txtInicio.setEnabled(false);

        txtTermino.setFormatterFactory(setFormatoData());
        txtTermino.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbArea)
                    .addComponent(lbInicio)
                    .addComponent(lbResponsavel)
                    .addComponent(lbCodigo)
                    .addComponent(lbEvento))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lbTermino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lbStatus)
                                .addGap(18, 18, 18)
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInicio)
                    .addComponent(lbTermino)
                    .addComponent(txtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsavel)
                    .addComponent(txtResponsavel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbArea)
                    .addComponent(lbStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEventoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEvento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public static DefaultFormatterFactory setFormatoData(){  
        MaskFormatter comFoco = null;  
        try   
        {   
            comFoco = new MaskFormatter("##/##/####"); 
            comFoco.setPlaceholderCharacter('_');
        }   
        catch (Exception pe) { }  
        DefaultFormatterFactory factory = new DefaultFormatterFactory(comFoco, comFoco);  
        return factory;  
    } 
    
    
    public void preencherComboCurso(){
        try {
            listaCurso = cursoDAO.ListaCurso();
        } catch (SQLException ex) {
            Logger.getLogger(EventoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Curso curso : listaCurso){
            cbCurso.addItem(curso.getNomeCurso());
        }
        
    }
    
     public void atualizarTabelaEvento(){
        evento = new Evento();
        
        try {
            listaEvento = eventoDAO.ListaEvento();
        } catch (SQLException ex) {
            Logger.getLogger(EventoView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        String dados[][] = new String[listaEvento.size()][7];
        int i = 0;
        for(Evento evento : listaEvento){
            dados[i][0] = String.valueOf(evento.getCodigoEvento());
            dados[i][1] = evento.getTituloEvento();
            dados[i][2] = evento.getInicioEvento();
            dados[i][3] = evento.getTerminoEvento();
            dados[i][4] = evento.getResponsavelEvento();
            //dados[i][5] = evento.getCursoEvento();
            dados[i][5] = evento.getStatusEvento();
            
            i++;
        }
        
        String tituloColuna[] = {"ID", "Titulo", "Inicio", "Termino", "Responsável", "Area", "Status"};
        DefaultTableModel tabelaEvento = new DefaultTableModel();
        tabelaEvento.setDataVector(dados, tituloColuna);
        tbEvento.setModel(new DefaultTableModel(dados, tituloColuna){
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        });
        
        tbEvento.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbEvento.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbEvento.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbEvento.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbEvento.getColumnModel().getColumn(4).setPreferredWidth(200);
        tbEvento.getColumnModel().getColumn(5).setPreferredWidth(200);
        tbEvento.getColumnModel().getColumn(5).setPreferredWidth(150);
        
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbEvento.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbEvento.setRowHeight(25);
        tbEvento.updateUI();
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         if(txtEvento.getText().isEmpty()||txtInicio.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha os campos");
            txtEvento.requestFocusInWindow();
        } else if(txtCodigo.getText().isEmpty()){
            evento = new Evento();
            evento.setTituloEvento(txtEvento.getText());
            evento.setInicioEvento(txtInicio.getText());
            evento.setTerminoEvento(txtTermino.getText());
            evento.setResponsavelEvento(txtResponsavel.getText());
            evento.setCursoEvento(listaCurso.get(cbCurso.getSelectedIndex()));
            evento.setStatusEvento((String) cbStatus.getSelectedItem());
    
             try {
                 eventoDAO.salvar(evento);
             } catch (SQLException ex) {
                 Logger.getLogger(EventoView.class.getName()).log(Level.SEVERE, null, ex);
             }
           
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            atualizarTabelaEvento();
            preparaSalvareCancelar();
            desativaCampos();
            limpaCamposEvento();
        } else{
            evento = new Evento();
            evento.setCodigoEvento(Integer.parseInt(txtCodigo.getText()));
            evento.setTituloEvento(txtEvento.getText());
            evento.setInicioEvento(txtInicio.getText());
            evento.setTerminoEvento(txtTermino.getText());
            evento.setResponsavelEvento(txtResponsavel.getText());
            evento.setCursoEvento(listaCurso.get(cbCurso.getSelectedIndex()));
            evento.setStatusEvento((String) cbStatus.getSelectedItem());
            
            try {
                eventoDAO.alterar(evento);
            } catch (SQLException ex) {
                Logger.getLogger(EventoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            atualizarTabelaEvento();
            preparaSalvareCancelar();
            desativaCampos();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tbEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEventoMouseClicked
        txtCodigo.setText(tbEvento.getValueAt(tbEvento.getSelectedRow(),0).toString());
        txtEvento.setText(tbEvento.getValueAt(tbEvento.getSelectedRow(),1).toString());
        txtInicio.setText(tbEvento.getValueAt(tbEvento.getSelectedRow(),2).toString());
        txtTermino.setText(tbEvento.getValueAt(tbEvento.getSelectedRow(),3).toString());
        txtResponsavel.setText(tbEvento.getValueAt(tbEvento.getSelectedRow(),4).toString());
        cbCurso.setSelectedItem(tbEvento.getValueAt(tbEvento.getSelectedRow(),5).toString());
        cbStatus.setSelectedItem(tbEvento.getValueAt(tbEvento.getSelectedRow(),6).toString());
        preparaSelecaoTabela();
    }//GEN-LAST:event_tbEventoMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um evento!");
        } else{
            evento = new Evento();
            evento.setCodigoEvento(Integer.parseInt(txtCodigo.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " +txtEvento.getText());
            
            if(confirma ==0){
                try {
                    eventoDAO.excluir(evento);
                } catch (SQLException ex) {
                Logger.getLogger(EventoView.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
                limpaCamposEvento();
                atualizarTabelaEvento();
                preparaExcluir();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCamposEvento();
        preparaNovo();
        ativaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        preparaAlterar();
        ativaCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposEvento();
        preparaSalvareCancelar();
        desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoActionPerformed

    }//GEN-LAST:event_cbCursoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed
    
    public void limpaCamposEvento(){
        txtCodigo.setText("");
        txtEvento.setText("");
        txtInicio.setText("");
        txtTermino.setText("");
        txtResponsavel.setText("");
        cbCurso.setSelectedItem("Todos");
        cbStatus.setSelectedItem("");
    }
    
    public void ativaCampos(){
        lbCodigo.setEnabled(true);
        lbEvento.setEnabled(true);
        txtEvento.setEnabled(true);
        lbInicio.setEnabled(true);
        txtInicio.setEnabled(true);
        lbTermino.setEnabled(true);
        txtTermino.setEnabled(true);
        lbResponsavel.setEnabled(true);
        txtResponsavel.setEnabled(true);
        lbArea.setEnabled(true);
        cbCurso.setEnabled(true);
        lbStatus.setEnabled(true);
        cbStatus.setEnabled(true);
    }
    
    public void desativaCampos(){
        lbCodigo.setEnabled(false);
        lbEvento.setEnabled(false);
        txtEvento.setEnabled(false);
        lbInicio.setEnabled(false);
        txtInicio.setEnabled(false);
        lbTermino.setEnabled(false);
        txtTermino.setEnabled(false);
        lbResponsavel.setEnabled(false);
        txtResponsavel.setEnabled(false);
        lbArea.setEnabled(false);
        cbCurso.setEnabled(false);
        lbStatus.setEnabled(false);
        cbStatus.setEnabled(false);
    }
    
    public void preparaNovo(){
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbEvento.setEnabled(false);
        tbEvento.clearSelection();
    }
    
    public void preparaSalvareCancelar(){
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tbEvento.setEnabled(true);
    }
    
    public void preparaSelecaoTabela(){
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    }
    
    public void preparaAlterar(){
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        tbEvento.setEnabled(false);
        tbEvento.clearSelection();
    }
    
    public void preparaExcluir(){
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbEvento;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTermino;
    private javax.swing.JTable tbEvento;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JFormattedTextField txtInicio;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JFormattedTextField txtTermino;
    // End of variables declaration//GEN-END:variables
}
